router:
  enabled: true
  enableCni: false
  enablePodEgress: false
  enableIbgp: true
  enableOverlay: true
  advertiseLoadbalancerIp: true
  advertiseExternalIp: true
  advertiseClusterIp: true
firewall:
  enabled: false
serviceProxy:
  enabled: false
