kubeProxyReplacement: probe

rollOutCiliumPods: true

ipam:
  mode: kubernetes

encryption:
  enabled: true
  nodeEncryption: false
  type: ipsec

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

bpf:
  masquerade: true

prometheus:
  enabled: true
